dependencies:
- name: etcd
  version: 0.4.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: etcd.deployChart
- name: zookeeper
  version: 1.1.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: zookeeper.deployChart
